# Generated by Django 2.0.7 on 2018-07-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Img_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('examples', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('examples', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role_type', models.CharField(choices=[('Docente', 'Docente'), ('Discente', 'Discente')], max_length=20)),
                ('role', models.CharField(choices=[('Coordenador', 'Coordenador'), ('Diretor Presidente', 'Diretor Presidente'), ('Diretor Vice-Presidente', 'Diretor Vice-Presidente'), ('Diretor de Projetos', 'Diretor de Projetos'), ('Gerente de Projetos', 'Gerente de Projetos'), ('Diretor de Negócios', 'Diretor de Negócios'), ('Gerente de Marketing', 'Gerente de Marketing'), ('Diretor de Processos Internos', 'Diretor de Processos Internos'), ('Gerente de Produtos Internos', 'Gerente de Produtos Internos'), ('Membro', 'Membro')], max_length=20)),
                ('pos_role', models.IntegerField(choices=[(1, 'Coordenador'), (2, 'Diretor Presidente'), (3, 'Diretor Vice-Presidente'), (4, 'Diretor de Projetos'), (5, 'Gerente de Projetos'), (6, 'Diretor de Negócios'), (7, 'Gerente de Marketing'), (8, 'Diretor de Processos Internos'), (9, 'Gerente de Processos Internos'), (10, 'Membro')])),
                ('about', models.TextField()),
                ('linkedin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Text_modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ewebsite.Service')),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ewebsite.Team'),
        ),
        migrations.AddField(
            model_name='img_text',
            name='text_modal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ewebsite.Text_modal'),
        ),
    ]
